### ISSUE TITLE
Logout login issue during change in screen size

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#27]
**Steps to reproduce**
1.Go to https://beta.utradea.com
2.  Log in to account
3. Click on Restore window size in your browser (User will logout automatically)
4. Now again click on Restore windows size back to normal (User will logged in automatically) 
Expected Result: User should not logged out of the account and URL should not change to mobile version
Actual Result : User logged out and again logged in automatically
**Video : http://somup.com/crnDoGDYC5**

**Comment by zhan1634** [comment]
There's a lot of bugs with regards to screen size, and this is not a major UI issue because the majority of individuals ar enot changing their screens every single second on sign on. The only one that does flag an issue is when you readjust the screen size to fit onto your desktop, but even then so there's a prompt asking you to stay. You will need to re-sign on because m.utradea.com is different than utradea.com - they are two different code bases with different authentication storage methods.
