### ISSUE TITLE
Previous 52 Week High 

### ISSUE THREAD

**Issue by JacksonDalton18** [Utradea-Inc/utradea-public#567]
I am currently sketching out some templates for alerts. One of the alerts is if the stock sets a new 52-Wk High.

Part of this alert would be noting that traders should look for the stock to close above their previous 52-Wk high. I cannot get that data, as there is only a 52Wk high option (that will update once it is crossed). Is there any way to make a field for the previous 52 wk high (maybe yesterday's 52-wk high, as it should have not crossed it yesterday)

Cheers!

**Comment by zhan1634** [comment]
So this is interesting, when it breaks the 52-week high, it broke it so the value will be the same. For ex. If bitcoin's 52 week high is 60K, and it just broke 60K, say its 60.001K. It broke the 52 week high but the amount is the same. The previous = the same because the trigger goes on once its broken.

**Comment by zhan1634** [comment]
Previous 52 week high would need to go way back in time, but we dont have that data. If i were to write a funtion to get the last high, it would be just under the 60K so I need to write a function where its not in the same time interval or get the last high excluding the last month's results. If you can think of how to approach this I can build it in.
