### ISSUE TITLE
After login with facebook, profile picture is not showing as per the facebook profile image.

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#64]
STR
1. Click on Facebook icon to login with facebook.
2. Check the Display Picture is reflecting as same as Facebook.
3. Observe the result.

Refer Screencast: http://somup.com/crnT10DBbx

**Comment by zhan1634** [comment]
Are you using a test Facebook Account?

**Comment by Ashish8822** [comment]
I have created a new account to test the facebook functionality. @zhan1634

**Comment by zhan1634** [comment]
This is not an issue on my end, it has to do with authentication from your test account end. Either you have not provided sufficient permissions to facebook, because I can see a facebook default picture is set which means it is coming through. Facebook has not provided utradea with your profile picture because of authentication on your end.
