### ISSUE TITLE
Check posibility to add an idea and add image in step 3

### ISSUE THREAD

**Issue by nonameuser2019** [Utradea-Inc/utradea-public#9]
Windows 10 Chrome

Steps of reproduce
1.go to https://beta.utradea.com/session/signup
2. Click on Post and Idea vidget
3. Add Idea
4. Select a ticket TS
5. on step Choice your analise you need to select general
6. on step general you nedd to add text and hyperlink and Image on text field
**Actual result** impossible add image
**Expected result** image added

**Comment by zhan1634** [comment]
Ctrl C + Ctrl V on image. I'm not sure what the issue is here. 

![Screenshot 2021-02-15 193908](https://user-images.githubusercontent.com/30502801/108005096-bc1a1b00-6fc5-11eb-92fd-911d7b02cfa2.png)
![Screenshot 2021-02-15 194021](https://user-images.githubusercontent.com/30502801/108005097-bc1a1b00-6fc5-11eb-9dce-46235a115059.png)

**Comment by zhan1634** [comment]
OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH you mean images located on your personal computer.

**Comment by zhan1634** [comment]
^ Please specify if that's the case.

**Comment by nonameuser2019** [comment]
This method of add photo not usability for your users
